### ISSUE TITLE
Unable to accept message in string or binary dataType

### ISSUE THREAD

**Issue by Akshatce** [Azure/azure-functions-rabbitmq-extension#72] opened 2019-10-27 08:33 UTC
Got error message while accepting string rather JSON

System.Private.CoreLib: Exception while executing function: Functions.consumer. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'message'. Newtonsoft.Json: Unexpected character encountered while parsing value: O. Path '', line 0, position 0.

In function.json I have mentioned dataType: string. Here is my function.json code.

**In function.json**

```
{
    "scriptFile": "__init__.py",
    "disabled": false,
    "bindings": [
        {
            "type": "rabbitMQTrigger",
            "connectionStringSetting": "RabbitMqConnection",
            "queueName": "queuename,
            "name": "message",
	    "dataType": "string"
        }
    ]
}
```

**In __init__.py:**

```
import logging

def main(message):
    logging.info("Receive message from output function: %s", message)
```

**Comment by jeffhollan** [comment] 2019-12-06 06:23
Can confirm - hit this as well

**Comment by geekwhocodes** [comment] 2019-12-09 06:43
This worked for me.

In init.py:

`def main(order) -> str:
    logging.info('Python queue trigger function processed a queue item: %s',
                 order)`

In function.json:

`{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "order",
      "type": "RabbitMQTrigger",
      "direction": "in",
      "queueName": "orders",
      "connection": "RabbitMQConnection"
    }
  ]
}`

**Comment by jeffhollan** [comment] 2020-10-15 22:43
Duplicate of #80

**Closed as completed by jeffhollan** 2020-10-15 22:43 UTC
Labels: enhancement, P2
