### ISSUE TITLE
rabbitmq trigger does not have any feature to specify durability to true or false.

### ISSUE THREAD

**Issue by kumarshubhu** [Azure/azure-functions-rabbitmq-extension#73] opened 2019-10-30 05:51 UTC
[RabbitMQTrigger("Rabbitmq.Model.Message")],
their is no way of specifying durability property of queue to true or false.

 public static class RabbitQueueTrigger
    {
        
        [FunctionName("RabbitQueueTrigger")]
        public static void Run(
        [RabbitMQTrigger("Rabbitmq.Model.Message")] Email inputMessage,
      ILogger log)
        {
            MailMessage message = new MailMessage();
            message.Sender = new MailAddress(inputMessage.Sender);
            message.From = message.Sender;
            message.To.Add(inputMessage.Reciever);
            message.IsBodyHtml = true;
            message.Priority = (MailPriority)2;
            message.Subject = inputMessage.subject;
            message.Body = inputMessage.body;
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
            smtpClient.Credentials = new System.Net.NetworkCredential()
            {
                UserName = "random@gmail.com",
                Password = "random"
            };
            smtpClient.EnableSsl = true;
            smtpClient.Send(message);
            log.LogInformation("C# RabbitQueueTrigger function processed a request.");
            log.LogInformation(inputMessage.body);
        }
    }

Getting below error :

Microsoft.Azure.WebJobs.Host: Error indexing method 'RabbitQueueTrigger'. RabbitMQ.Client: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'Rabbitmq.Model.Message' in vhost '/': received 'false' but current is 'true'", classId=50, methodId=10, cause=.
[30-10-2019 05:39:59] Error indexing method 'RabbitQueueTrigger'

**Comment by geekwhocodes** [comment] 2019-10-30 08:29
Duplicate of issue #68

**Comment by fabiocav** [comment] 2019-10-30 19:49
Closing this as a duplicate.

**Closed as completed by fabiocav** 2019-10-30 19:49 UTC
